### ISSUE TITLE
Git.shortlog! running forever...

### ISSUE THREAD

**Issue by kitplummer** [danhper/elixir-git-cli#14]
Heyo.  Trying to get to the `git shortlog -s -n` command, but it never returns when I try to use the library with `Git.shortlog! repo, ["-s", "-n"]`.  Any ideas?

**Comment by kitplummer** [comment]
Thought it might be in my env but add the call to the "clone" test in the lib:

```
1) test clone (GitTest)
     test/git_test.exs:10
     ** (ExUnit.TimeoutError) test timed out after 60000ms. You can change the timeout:

       1. per test by setting "@tag timeout: x" (accepts :infinity)
       2. per test module by setting "@moduletag timeout: x" (accepts :infinity)
       3. globally via "ExUnit.start(timeout: x)" configuration
       4. by running "mix test --timeout x" which sets timeout
       5. or by running "mix test --trace" which sets timeout to infinity
          (useful when using IEx.pry/0)

     where "x" is the timeout given as integer in milliseconds (defaults to 60_000).

     code: {:ok, output} = Git.shortlog! repo
     stacktrace:
       (elixir) lib/system.ex:808: System.do_cmd/3
       (elixir) lib/system.ex:798: System.cmd/3
       (git_cli) lib/git.ex:104: Git.execute_command/4
       (git_cli) lib/git.ex:83: Git.shortlog!/2
       test/git_test.exs:19: (test)
       (ex_unit) lib/ex_unit/runner.ex:355: ExUnit.Runner.exec_test/1
       (stdlib) timer.erl:166: :timer.tc/1
       (ex_unit) lib/ex_unit/runner.ex:306: anonymous fn/4 in ExUnit.Runner.spawn_test_monitor/4


21:43:39.386 [error] GenServer #PID<0.274.0> terminating
** (stop) killed
Last message: {:EXIT, #PID<0.273.0>, :killed}
State: #MapSet<["/var/folders/lm/dv8hd46901j00z5mj97jsj9r0000gn/T/elixir-git-cli-1566351759-27238-1jrqyvi"]>
```

Sorry, I'm not too familiar with Elixir or debugging, otherwise I keep digging.

**Comment by GuillaumeMilan** [comment]
Can you try to execute your command manually in your repository

```time git shortlog -s -n```

Does it succeed in less than 60s?

**Comment by kitplummer** [comment]
Yes.  The command returns immediately.

**Comment by kitplummer** [comment]
Don't know why...but `System.cmd "git", ["shortlog", "-s"]` just hangs it up.

**Comment by danhper** [comment]
Hi,
I managed to reproduce the issue but I'm not sure what is the best way to fix this.
Internally, this module uses `System.cmd`, which uses `Port.open`, which then calls Erlang's `open_port`.
So basically, the following is executed

```
p = :erlang.open_port({:spawn_executable, '/bin/git'}, [:binary, {:args, ["--no-pager", "shortlog"]}])
```

After running this, the port is created, but if we try to `flush()` the mailbox nothing is there, which means that neither the data nor the message to signal the process has been terminated is there.
As `System.cmd` waits for this to terminate, it hangs forever.
`ps aux | grep shortlog` shows that shortlog is actually running, but if we try to attach the process with `sudo strace -p PID`, we can see that the `git shortlog` process is trying to read something from stdin: there is a pending `read(0, `

Checking the `git shortlog` documentation

> If no revisions are passed on the command line and either standard input is not a terminal or there is no current branch, git shortlog will output a summary of the log read from standard input, without reference to the current repository.

Which means that `git` thinks it can read from `stdin`. It should simply be a matter of closing the `stdin` of the erlang port but I could not find if there is any way to do this in Erlang (which I find very surprising). The other solution would be to force git not to read from the stdin but I am not sure how to do this either.

In the meanwhile, a simple workaround is to pass `HEAD` so that git does not try to read from stdin:

```
Git.shortlog!(repo, ["HEAD"])
```

Please let me know if you find any more permanent fix to this issue.

**Comment by danhper** [comment]
I added an ad-hoc solution for shortlog but I would rather have something we can be sure works with every git command so if you have any good idea, please comment here or open a PR or issue.
Thanks!

**Comment by kitplummer** [comment]
Sorry, meant to report this back last night and got caught up with things:

https://stackoverflow.com/questions/57618603/elixir-system-cmd-git-shortlog-doesnt-ever-return-why?noredirect=1#comment101691894_57618603

Basically confirms what you posted above.  Passing in the branch works.  Yeah, it'd be good if there's a way to protect a user from running into this from within your library.  I'll come back to this in a bit - need to catch up with the thing I'm building first.  :D
